services:
  db:
    image: postgres:16-alpine
    container_name: jobflow-db
    environment:
      POSTGRES_DB: jobflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
