# Generated by Django 5.2.12 on 2026-04-20 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_id', models.IntegerField(unique=True)),
                ('source', models.CharField(default='linkedin', max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('seniority', models.CharField(default='MID', max_length=20)),
                ('experience_years', models.FloatField(default=0.0)),
                ('education', models.CharField(default='BACHELOR', max_length=20)),
                ('text_summary', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'labeling_cv',
            },
        ),
        migrations.CreateModel(
            name='LabelingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('seniority', models.CharField(default='MID', max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('text_summary', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'labeling_job',
            },
        ),
        migrations.CreateModel(
            name='PairQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_overlap_score', models.FloatField(default=0.0)),
                ('bm25_score', models.FloatField(default=0.0)),
                ('selection_reason', models.CharField(choices=[('medium_overlap', 'Medium Overlap'), ('high_overlap', 'High Overlap'), ('hard_negative', 'Hard Negative'), ('random', 'Random')], max_length=30)),
                ('priority', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('labeled', 'Labeled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('split', models.CharField(default='train', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='labeling.labelingcv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='labeling.labelingjob')),
            ],
            options={
                'db_table': 'labeling_pair_queue',
                'ordering': ['priority', 'cv_id'],
                'unique_together': {('cv', 'job')},
            },
        ),
        migrations.CreateModel(
            name='HumanLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_fit', models.IntegerField(choices=[(0, 'Không phù hợp'), (1, 'Tạm được'), (2, 'Tốt')])),
                ('seniority_fit', models.IntegerField(choices=[(0, 'Không phù hợp'), (1, 'Tạm được'), (2, 'Tốt')])),
                ('experience_fit', models.IntegerField(choices=[(0, 'Không phù hợp'), (1, 'Tạm được'), (2, 'Tốt')])),
                ('domain_fit', models.IntegerField(choices=[(0, 'Không phù hợp'), (1, 'Tạm được'), (2, 'Tốt')])),
                ('overall', models.IntegerField(choices=[(0, 'Không phù hợp'), (1, 'Phù hợp'), (2, 'Rất phù hợp')])),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labeling.pairqueue')),
            ],
            options={
                'db_table': 'labeling_human_label',
            },
        ),
    ]
