# Generated by Django 5.2.12 on 2026-04-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=500)),
                ('model', models.CharField(help_text='e.g. gpt-4o-mini, claude-haiku-4-5', max_length=100)),
                ('base_url', models.URLField(help_text='OpenAI-compatible base URL', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
