# Generated by Django 5.2.12 on 2026-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.URLField(help_text='Base URL, e.g. https://api.openai.com/v1', max_length=500),
        ),
    ]
