# Generated by Django 5.2.12 on 2026-04-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_add_llm_call_log'),
        ('llm', '0003_alter_llmprovider_base_url'),
    ]

    operations = [
    ]
