# Generated by Django 5.2.12 on 2026-03-31 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('num_jobs', models.IntegerField(default=0)),
                ('num_cvs', models.IntegerField(default=0)),
                ('num_pairs', models.IntegerField(default=0)),
                ('num_skills', models.IntegerField(default=0)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('best_epoch', models.IntegerField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('reranker_accuracy', models.FloatField(blank=True, null=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('checkpoint_path', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('eligible', models.BooleanField(default=False)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('seniority_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cvs.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'db_table': 'match_results',
                'ordering': ['-score'],
                'unique_together': {('cv', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('relevant', 'Relevant'), ('not_relevant', 'Not Relevant')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='matching.matchresult')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
