# Generated by Django 5.2.12 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Technical'), (1, 'Soft'), (2, 'Tool'), (3, 'Domain')], default=0)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['canonical_name'],
            },
        ),
    ]
