# Generated by Django 5.2.12 on 2026-03-31 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('logo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('website_url', models.URLField(blank=True, default='', max_length=1000)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('logo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On Site'), ('other', 'Other')], default='other', max_length=20)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField(default=0)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('applicant_count', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=3)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='skills.skill')),
            ],
            options={
                'db_table': 'job_skills',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, through='jobs.JobSkill', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.platform'),
        ),
        migrations.CreateModel(
            name='CompanyPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(blank=True, default='', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles', to='jobs.company')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='jobs.platform')),
            ],
            options={
                'db_table': 'company_platforms',
                'unique_together': {('company', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='platforms',
            field=models.ManyToManyField(blank=True, through='jobs.CompanyPlatform', to='jobs.platform'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('platform', 'fingerprint')},
        ),
    ]
