# Generated by Django 5.2.12 on 2026-03-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField()),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField(default=0)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=3)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'job_skills',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, through='jobs.JobSkill', to='skills.skill'),
        ),
    ]
