# Generated by Django 5.2.12 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jd_extraction_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdextractionrecord',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
