# Generated by Django 5.2.12 on 2026-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_content_hash_and_role_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdextractionrecord',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
