# Generated by Django 5.2.12 on 2026-03-31 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('file_name', models.CharField(blank=True, default='', max_length=300)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_text', models.TextField(blank=True, default='')),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('experience_years', models.FloatField(default=0.0)),
                ('education', models.IntegerField(choices=[(0, 'None'), (1, 'College'), (2, 'Bachelor'), (3, 'Master'), (4, 'Phd')], default=2)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('source_category', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(default=3)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills', to='cvs.cv')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills', to='skills.skill')),
            ],
            options={
                'db_table': 'cv_skills',
                'unique_together': {('cv', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(blank=True, through='cvs.CVSkill', to='skills.skill'),
        ),
    ]
