# Generated by Django 5.2.12 on 2026-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('experience_years', models.FloatField(default=0.0)),
                ('education', models.IntegerField(choices=[(0, 'None'), (1, 'College'), (2, 'Bachelor'), (3, 'Master'), (4, 'Phd')], default=2)),
                ('parsed_text', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'cv_skills',
            },
        ),
    ]
