# Generated by Django 5.2.12 on 2026-03-30 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills', to='cvs.cv'),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(blank=True, through='cvs.CVSkill', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='cvskill',
            unique_together={('cv', 'skill')},
        ),
    ]
