# Generated by Django 5.2.12 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_add_candidate_name_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='role_category',
            field=models.CharField(blank=True, default='other', max_length=20),
        ),
    ]
