# Generated by Django 5.2.12 on 2026-04-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_add_content_hash_and_role_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVExtractionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_source', models.CharField(blank=True, default='', max_length=50)),
                ('filter_source_categories', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('done_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_extraction_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_msg', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cvs.cvextractionbatch')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_records', to='cvs.cv')),
            ],
            options={
                'db_table': 'cv_extraction_records',
                'ordering': ['cv_id'],
            },
        ),
    ]
